#server:
#  port: 8081
#  context-path: /cs

# datasource
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/noname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
          stat-view-servlet:
            allow: true
          max-active: 10
          min-idle: 1
    mvc:
      view:
        prefix:
    redis:
      host: 192.168.231.136
      port: 6739
      timeout: 10000
      pool:
        max-idle: 500
        max-wait: 10000


mybatis:
    type-aliases-package: com.noname.entity
    mapper-locations: classpath:mybatis/xml/*.xml

## 如果自定义一个mapper继承tk的mapper (mapper和@mapper冲突问题) 则需要配置
mapper:
    mappers:
        - com.noname.util.BaseMapper
    not-empty: false
    identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level: debug;
