server:
  port: 8080
#  context-path: /cs


# datasource
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/noname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
          stat-view-servlet:
            allow: true
          max-active: 10
          min-idle: 1

    redis:
      host: 192.168.144.129
      port: 6379
      timeout: 10000
      pool:
        max-idle: 200
        max-wait: 2000
#      password: redis@123
    cache:
      type: redis


mybatis:
    type-aliases-package: com.noname.entity
    mapper-locations: classpath:com/noname/mapper/xml/*.xml


## 如果自定义一个mapper继承tk的mapper (mapper和@mapper冲突问题) 则需要配置
mapper:
    mappers:
        - com.noname.util.BaseMapper
    not-empty: false
    identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level: debug;
